language: node_js
node_js:
- node
deploy:
  provider: npm
  email: mail@qwtel.com
  api_key:
    secure: jldwzWTmVnpbKoEVbehlGBzUCI9nLCsl3gSNRsprYRI32RZW0ZJWqdxRAxaNQl/qr0vspSEyhzbmNpXn0ZG6hlrka09YhQnWrJ1Ytgm8/flRfsyjG1od8AW+qIzvXsMKK1H/6OIRaNj4BmOhfhStC164YAyZgDaG1k1/UasvX15UR5qd1e4Se/SaMGEZJ3yF+HvH9hiqmXFJOGIedG0eFrjNqWPuLeizilLalwicdvPJa0jyfV7d+o9Sexl67k8SKLbzvhTDAhK0g9OKntx8dhmo4j8owcxAJr5s+SLRKgK7weQf5nXER0NkaGsiZHK3Lqc5IyZ2TkWpL9nd7nxCzUJQJXs52IY0bcLJYa7wzPo3YPjUQXKUgEqldhLUPn75jIW2yj6hCd80nomzsmV3Uo2x0zvWsh9Bm/6YZ0zlfK16mWSosAZJu1cc4VPevqFFGKlIqBE3Nhek4DSOhmw9cMz0rU9ZRv25dyo6dg1Uq1rgxbtR4cqn0FcCtDIXlXpmC/4KqN01P7QbAY1OvCAHe0UoeYrubPwlXu4eU2MbI5OO2UsC6uaOMIohXvOle3Blse07yMaiI4XxLg/Z1Rxl1sjXFwZMhtba6lMo5x1QO+EdxuoaRU1M2rHh32/P9NoX0MfwYUBe+tzvakGM0E+gH71AO8KyCXfAH7oen6v3vEA=
  on:
    tags: true
    repo: qwtel/hy-img
