/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HyImg {
    'alt': string;
    'decoding': 'sync' | 'async' | 'auto';
    'h': number;
    'loadImage': () => void;
    'root': string;
    'rootMargin': string;
    'src': string;
    'srcset': string;
    'useMap': string;
    'w': number;
  }
  interface HyImgAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'decoding'?: 'sync' | 'async' | 'auto';
    'h'?: number;
    'root'?: string;
    'rootMargin'?: string;
    'src'?: string;
    'srcset'?: string;
    'useMap'?: string;
    'w'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HyImg': Components.HyImg;
  }

  interface StencilIntrinsicElements {
    'hy-img': Components.HyImgAttributes;
  }


  interface HTMLHyImgElement extends Components.HyImg, HTMLStencilElement {}
  var HTMLHyImgElement: {
    prototype: HTMLHyImgElement;
    new (): HTMLHyImgElement;
  };

  interface HTMLElementTagNameMap {
    'hy-img': HTMLHyImgElement
  }

  interface ElementTagNameMap {
    'hy-img': HTMLHyImgElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
